name: Train YOLOv4

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip build-essential libopencv-dev

      - name: Install Python tools
        run: pip install gdown

      - name: Prepare dataset
        run: bash scripts/prepare_data.sh

      - name: Build Darknet
        run: |
          git clone https://github.com/AlexeyAB/darknet.git
          cd darknet
          sed -i 's/GPU=0/GPU=1/' Makefile
          sed -i 's/CUDNN=0/CUDNN=1/' Makefile
          sed -i 's/CUDNN_HALF=0/CUDNN_HALF=1/' Makefile
          sed -i 's/OPENCV=0/OPENCV=1/' Makefile
          make -j$(nproc)

      - name: Download pretrained weights
        run: wget -P darknet/ https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4.conv.137

      - name: Train YOLOv4
        run: |
          cd darknet
          ./darknet detector train ../data/obj.data ../cfg/yolov4-dental.cfg yolov4.conv.137 -dont_show -map

      - name: Upload trained weights
        uses: actions/upload-artifact@v4
        with:
          name: yolov4-dental-weights
          path: darknet/backup/*.weights
